import Head from "next/head";

import Header from "@/components/Header";

const Layout = ({ children, user, title, courseTitle }) => {
  return (
    <>
      <Head>
        <title>{title ? `${title} | WebDev` : "WebDev"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="d-flex flex-column h-100vh">
        <Header user={user} title={title} courseTitle={courseTitle} />
        <main className="flex-auto main">{children}</main>
        <footer className="footer py-3 bg-dark text-white">
          <div className="container fw-bold d-flex justify-content-between">
            <div>Vit Poll</div>
            <div>&copy; {new Date().getFullYear()}</div>
          </div>
        </footer>
      </section>
    </>
  );
};

export default Layout;
